# Metrics collection interval
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Scrape Prometheus itself and the Order API.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
        # Identify Prometheus's own metrics.
        labels:
          app: "prometheus"
    scrape_native_histograms: true
  - job_name: "order-api"
    static_configs:
      - targets: ["host.docker.internal:8080"]
